[pytest]
python_files = *_test.py test_*.py
python_classes = Test*
python_functions = test_*
markers =
    users: Маркировка для тестов, связанных с пользователями.
    authentication: Маркировка для тестов аутентификации.
    regression: Маркировка для регрессионных тестов.
    smoke: Маркировка для смоук тестов.
    critical: Маркировка для критично важных тестов.
    api: Маркировка для апи тестов.
    slow: Маркировка для медленных тестов.
    fast: Маркировка для быстрых тестов.